import { FactoryFeed } from '@/types';

export const FACTORY_FEEDS: FactoryFeed[] = [
  // ==========================================
  // PROYEM (MATLI HOLDİNG) - TÜM SÜT YEMİ ÇEŞİTLERİ
  // ==========================================
  {
    id: 'proyem-pro-18',
    brand: 'Proyem',
    name: 'Proyem Pro 18 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Ekonomik Süt Yemi',
    protein: 18.0,
    starch: 25.5,
    dryMatter: 88.0,
    energyME: 2620,
    cellulose: 10.0,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 13.20,
    bagWeight: 50,
    description: 'Orta ve düşük verimli sağmallar ile laktasyonun son dönemindeki inekler için ekonomik ve güvenli süt yemi.',
  },
  {
    id: 'proyem-pro-19',
    brand: 'Proyem',
    name: 'Proyem Pro 19 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 26.5,
    dryMatter: 88.0,
    energyME: 2700,
    cellulose: 9.5,
    calcium: 1.1,
    phosphorus: 0.6,
    approxPrice: 13.80,
    bagWeight: 50,
    description: 'Orta ve yüksek verimli sağmal inekler için dengeli enerji ve protein kaynağı. Mısır silajı ve yoncalı rasyonlarla tam uyumludur.',
  },
  {
    id: 'proyem-pro-20',
    brand: 'Proyem',
    name: 'Proyem Pro 20 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Dengeli Süt Yemi',
    protein: 20.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2750,
    cellulose: 9.0,
    calcium: 1.15,
    phosphorus: 0.62,
    approxPrice: 14.50,
    bagWeight: 50,
    description: 'Günde 22-28 litre süt veren sağmallar için ideal protein-enerji oranına sahip süt yemi.',
  },
  {
    id: 'proyem-pro-21',
    brand: 'Proyem',
    name: 'Proyem Pro 21 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim Süt Yemi',
    protein: 21.0,
    starch: 28.0,
    dryMatter: 88.0,
    energyME: 2800,
    cellulose: 8.5,
    calcium: 1.2,
    phosphorus: 0.65,
    approxPrice: 15.20,
    bagWeight: 50,
    description: 'Günde 28 litre ve üzeri süt veren pik dönemindeki sağmallar için yüksek bypass protein ve enerji içerir.',
  },
  {
    id: 'proyem-pro-22',
    brand: 'Proyem',
    name: 'Proyem Pro 22 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Pik Dönemi Süt Yemi',
    protein: 22.0,
    starch: 28.5,
    dryMatter: 88.0,
    energyME: 2820,
    cellulose: 8.2,
    calcium: 1.25,
    phosphorus: 0.66,
    approxPrice: 15.80,
    bagWeight: 50,
    description: '30 litrenin üzerindeki yüksek verimli ineklerin süt pikini korur, negatif enerji dengesini sınırlar.',
  },
  {
    id: 'proyem-pro-4x4',
    brand: 'Proyem',
    name: 'Proyem Pro 4x4 Süt Yemi (20 HP)',
    category: 'SUT_YEMI',
    categoryLabel: 'Özel Seri Performans',
    protein: 20.0,
    starch: 28.8,
    dryMatter: 88.0,
    energyME: 2800,
    cellulose: 8.4,
    calcium: 1.18,
    phosphorus: 0.63,
    approxPrice: 15.00,
    bagWeight: 50,
    description: 'Rumen sindirimini hızlandıran özel mayalı ve organik mineralli 4 mevsim performans yemi.',
  },
  {
    id: 'proyem-protek-laktasyon',
    brand: 'Proyem',
    name: 'Proyem Protek Laktasyon',
    category: 'SUT_YEMI',
    categoryLabel: 'Özel Seri Laktasyon',
    protein: 20.0,
    starch: 29.0,
    dryMatter: 88.0,
    energyME: 2850,
    cellulose: 8.0,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 15.50,
    bagWeight: 50,
    description: 'Tahıl ilavesi gerektirmeyen tek başına dengeli fabrika yemi formülasyonu. Yüksek nişasta ve enerji yoğunluğu.',
  },
  {
    id: 'proyem-pro-dogus',
    brand: 'Proyem',
    name: 'Proyem Pro Doğuş (Doğum Sonrası Fresh)',
    category: 'SUT_YEMI',
    categoryLabel: 'Fresh Dönemi (0-21 Gün)',
    protein: 21.5,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2850,
    cellulose: 8.5,
    calcium: 1.3,
    phosphorus: 0.7,
    approxPrice: 16.20,
    bagWeight: 50,
    description: 'Yeni doğum yapmış sağmalların hızla toparlanması, ketozis ve abomazum deplasmanını önlemek için glukojenik öncüllerle zenginleştirilmiştir.',
  },
  {
    id: 'proyem-pro-enerji',
    brand: 'Proyem',
    name: 'Proyem Pro Enerji Süt Yemi (18 HP / 2850 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Enerji Süt Yemi',
    protein: 18.0,
    starch: 31.0,
    dryMatter: 88.0,
    energyME: 2850,
    cellulose: 7.8,
    calcium: 1.0,
    phosphorus: 0.55,
    approxPrice: 14.20,
    bagWeight: 50,
    description: 'Proteini yonca gibi kaba yemlerden karşılanan işletmelerde negatif enerji dengesini kapatmak için yüksek nişastalı formül.',
  },
  {
    id: 'proyem-pro-balans',
    brand: 'Proyem',
    name: 'Proyem Pro Balans Dengeleyici (28 HP)',
    category: 'DENGELIYICI',
    categoryLabel: 'Protein Dengeleme Konsantresi',
    protein: 28.0,
    starch: 18.0,
    dryMatter: 89.0,
    energyME: 2650,
    cellulose: 7.0,
    calcium: 1.8,
    phosphorus: 0.8,
    approxPrice: 18.50,
    bagWeight: 50,
    description: 'Çiftlikte bol miktarda mısır silajı ve tahıl kırması kullanıldığında proteini dengelemek için tasarlanmış konsantre yem.',
  },
  {
    id: 'proyem-pro-41',
    brand: 'Proyem',
    name: 'Proyem Pro 41 Konsantre Tamamlayıcı (%41 HP)',
    category: 'DENGELIYICI',
    categoryLabel: 'Süper Protein Konsantresi',
    protein: 41.0,
    starch: 11.0,
    dryMatter: 90.0,
    energyME: 2500,
    cellulose: 6.5,
    calcium: 2.2,
    phosphorus: 1.1,
    approxPrice: 22.50,
    bagWeight: 50,
    description: 'Yüksek verimli işletmelerde kendi tahılını kıran üreticiler için soya ve bypass protein bazlı süper konsantre.',
  },
  {
    id: 'proyem-pro-cizgi',
    brand: 'Proyem',
    name: 'Proyem Pro Çizgi Süt Yemi (19 HP)',
    category: 'SUT_YEMI',
    categoryLabel: 'Verimlilik Serisi',
    protein: 19.0,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2680,
    cellulose: 9.6,
    calcium: 1.1,
    phosphorus: 0.58,
    approxPrice: 13.60,
    bagWeight: 50,
    description: 'Orta ölçekli aile işletmeleri için maliyet/performans dengesi optimize edilmiş süt yemi.',
  },

  // ==========================================
  // CP YEM - TÜM SÜT YEMİ ÇEŞİTLERİ
  // ==========================================
  {
    id: 'cp-sigir-sut-18',
    brand: 'CP Yem',
    name: 'CP Sığır Süt 18 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Ekonomik Süt Yemi',
    protein: 18.0,
    starch: 25.0,
    dryMatter: 88.0,
    energyME: 2600,
    cellulose: 10.2,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 13.00,
    bagWeight: 50,
    description: 'Orta verimli sürüler ve laktasyon sonu sağmallar için ekonomik ve güvenli süt yemi.',
  },
  {
    id: 'cp-sut-19',
    brand: 'CP Yem',
    name: 'CP Süt Yemi 19 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2680,
    cellulose: 9.8,
    calcium: 1.1,
    phosphorus: 0.58,
    approxPrice: 13.70,
    bagWeight: 50,
    description: 'Tüm laktasyon periyodunda güvenle kullanılabilen, sindirilebilir lif ve nişasta dengesi optimum klasik CP süt yemi.',
  },
  {
    id: 'cp-sut-20',
    brand: 'CP Yem',
    name: 'CP Süt Yemi 20 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Dengeli Laktasyon',
    protein: 20.0,
    starch: 27.0,
    dryMatter: 88.0,
    energyME: 2740,
    cellulose: 9.2,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 14.40,
    bagWeight: 50,
    description: 'Süt verimini istikrarlı tutarken döl verimini destekleyen dengeli CP karma yemi.',
  },
  {
    id: 'cp-sut-21',
    brand: 'CP Yem',
    name: 'CP Süt Yemi 21 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim Süt Yemi',
    protein: 21.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2780,
    cellulose: 8.8,
    calcium: 1.2,
    phosphorus: 0.62,
    approxPrice: 15.00,
    bagWeight: 50,
    description: 'Yüksek süt verimi hedeflenen işletmelerde süt pikini uzatır, kondisyon kaybını engeller.',
  },
  {
    id: 'cp-sut-22',
    brand: 'CP Yem',
    name: 'CP Süt Yemi 22 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Pik Laktasyon',
    protein: 22.0,
    starch: 28.2,
    dryMatter: 88.0,
    energyME: 2820,
    cellulose: 8.4,
    calcium: 1.25,
    phosphorus: 0.65,
    approxPrice: 15.70,
    bagWeight: 50,
    description: 'Yüksek laktasyon verimi ve genetik potansiyeli yüksek ineklerde süt yağı ve proteinini korur.',
  },
  {
    id: 'cp-premium-sut-23',
    brand: 'CP Yem',
    name: 'CP Premium Süt 23 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Premium Pik Dönemi',
    protein: 23.0,
    starch: 29.0,
    dryMatter: 88.0,
    energyME: 2850,
    cellulose: 8.0,
    calcium: 1.3,
    phosphorus: 0.68,
    approxPrice: 16.50,
    bagWeight: 50,
    description: 'Yüksek genetik kapasiteli sağmallar için zenginleştirilmiş bypass protein, iz mineral ve enerji kombinasyonu.',
  },
  {
    id: 'cp-super-sut-20',
    brand: 'CP Yem',
    name: 'CP Süper Süt 20 HP / 2750 ME',
    category: 'SUT_YEMI',
    categoryLabel: 'Süper Seri',
    protein: 20.0,
    starch: 28.0,
    dryMatter: 88.0,
    energyME: 2750,
    cellulose: 8.9,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 14.60,
    bagWeight: 50,
    description: 'Hızlı sindirilen karbonhidratlar ve kaliteli protein fraksiyonları ile yüksek süt pikine ulaştırır.',
  },
  {
    id: 'cp-mega-sut-21',
    brand: 'CP Yem',
    name: 'CP Mega Süt Yemi (21 HP / 2850 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Mega Enerji & Protein',
    protein: 21.0,
    starch: 29.5,
    dryMatter: 88.0,
    energyME: 2850,
    cellulose: 8.0,
    calcium: 1.2,
    phosphorus: 0.65,
    approxPrice: 15.60,
    bagWeight: 50,
    description: 'Silaj ağırlıklı rasyonlarda yüksek enerji açığını kapatan mega yoğunluklu süt yemi.',
  },
  {
    id: 'cp-aksiyon-20',
    brand: 'CP Yem',
    name: 'CP Aksiyon Süt Yemi (20 HP)',
    category: 'SUT_YEMI',
    categoryLabel: 'Aksiyon Serisi',
    protein: 20.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2720,
    cellulose: 9.2,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 14.30,
    bagWeight: 50,
    description: 'Yem tüketimini tetikleyen aroma ve iştah artırıcı bileşenlerle formüle edilmiş aksiyon serisi.',
  },
  {
    id: 'cp-10nmr',
    brand: 'CP Yem',
    name: 'CP 10NMR Özel Laktasyon Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Teknoloji Serisi',
    protein: 21.5,
    starch: 28.5,
    dryMatter: 88.0,
    energyME: 2820,
    cellulose: 8.3,
    calcium: 1.25,
    phosphorus: 0.65,
    approxPrice: 16.00,
    bagWeight: 50,
    description: 'Rumen mikrobiyotasını optimize eden CP küresel Ar-Ge destekli özel laktasyon rasyon yemi.',
  },

  // ==========================================
  // TARIM KREDİ YEM (TÜRKİYE TARIM KREDİ KOOP.)
  // ==========================================
  {
    id: 'tkyem-sigir-sut-18',
    brand: 'Tarım Kredi',
    name: 'Tarım Kredi Sığır Süt 18 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 18.0,
    starch: 25.0,
    dryMatter: 88.0,
    energyME: 2600,
    cellulose: 10.0,
    calcium: 1.1,
    phosphorus: 0.55,
    approxPrice: 13.10,
    bagWeight: 50,
    description: 'Tarım Kredi Kooperatifleri güvencesiyle üretilmiş ekonomik ve güvenli süt yemi.',
  },
  {
    id: 'tkyem-sigir-sut-19',
    brand: 'Tarım Kredi',
    name: 'Tarım Kredi Sığır Süt 19 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Dengeli Süt Yemi',
    protein: 19.0,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2680,
    cellulose: 9.5,
    calcium: 1.15,
    phosphorus: 0.58,
    approxPrice: 13.70,
    bagWeight: 50,
    description: 'Türkiye genelinde en çok kullanılan dengeli Tarım Kredi süt yemi.',
  },
  {
    id: 'tkyem-enerji-sut-19',
    brand: 'Tarım Kredi',
    name: 'Tarım Kredi Enerji Süt 19 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Enerji',
    protein: 19.0,
    starch: 28.5,
    dryMatter: 88.0,
    energyME: 2800,
    cellulose: 8.8,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 14.50,
    bagWeight: 50,
    description: 'Yonca ve çayır otu tüketen sürülerde enerji ihtiyacını karşılamak için yükseltilmiş tahıllı formül.',
  },
  {
    id: 'tkyem-sigir-sut-20',
    brand: 'Tarım Kredi',
    name: 'Tarım Kredi Sığır Süt 20 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Verimlilik Süt Yemi',
    protein: 20.0,
    starch: 27.0,
    dryMatter: 88.0,
    energyME: 2740,
    cellulose: 9.0,
    calcium: 1.2,
    phosphorus: 0.62,
    approxPrice: 14.40,
    bagWeight: 50,
    description: 'Süt verimini pik seviyelerde tutmak için zengin protein ve dengeli nişasta.',
  },
  {
    id: 'tkyem-sigir-sut-21',
    brand: 'Tarım Kredi',
    name: 'Tarım Kredi Sığır Süt 21 HP (Bypass Destekli)',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim & Pik',
    protein: 21.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2780,
    cellulose: 8.7,
    calcium: 1.25,
    phosphorus: 0.65,
    approxPrice: 15.00,
    bagWeight: 50,
    description: 'Erken laktasyondaki ineklerin yoğun protein ve enerji ihtiyacını karşılamak için bypass protein takviyeli.',
  },
  {
    id: 'tkyem-bereket-sut-21',
    brand: 'Tarım Kredi',
    name: 'Tarım Kredi Bereket Süt 21 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Özel Seri Bereket',
    protein: 21.0,
    starch: 28.5,
    dryMatter: 88.0,
    energyME: 2820,
    cellulose: 8.3,
    calcium: 1.25,
    phosphorus: 0.65,
    approxPrice: 15.30,
    bagWeight: 50,
    description: 'Kooperatif üreticilerinin yüksek süt verimi için geliştirdiği ekstra nişasta ve enerji içeren özel seri.',
  },
  {
    id: 'tkyem-extra-sut-24',
    brand: 'Tarım Kredi',
    name: 'Tarım Kredi Extra Süt 24 HP Konsantre',
    category: 'DENGELIYICI',
    categoryLabel: 'Yüksek Protein Konsantre',
    protein: 24.0,
    starch: 22.0,
    dryMatter: 89.0,
    energyME: 2700,
    cellulose: 8.0,
    calcium: 1.5,
    phosphorus: 0.75,
    approxPrice: 16.80,
    bagWeight: 50,
    description: 'Kendi arpa ve mısırını kullanan işletmelerde rasyon proteinini hızlıca yükselten konsantre süt yemi.',
  },

  // ==========================================
  // ABALIOĞLU YEM - TÜM SÜT YEMİ ÇEŞİTLERİ
  // ==========================================
  {
    id: 'abalioglu-sut-18',
    brand: 'Abalıoğlu',
    name: 'Abalıoğlu Süt Yemi 18 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Ekonomik Süt Yemi',
    protein: 18.0,
    starch: 25.0,
    dryMatter: 88.0,
    energyME: 2620,
    cellulose: 10.0,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 13.10,
    bagWeight: 50,
    description: 'Laktasyon sonundaki hayvanların kondisyonunu düzeltirken ekonomik süt üretimi sağlar.',
  },
  {
    id: 'abalioglu-sut-19',
    brand: 'Abalıoğlu',
    name: 'Abalıoğlu Süt Yemi 19 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2700,
    cellulose: 9.2,
    calcium: 1.1,
    phosphorus: 0.6,
    approxPrice: 13.60,
    bagWeight: 50,
    description: 'Abalıoğlu kalitesiyle hazırlanmış, rumen mikroflorasını destekleyen dengeli enerji-protein yapısı.',
  },
  {
    id: 'abalioglu-sut-20',
    brand: 'Abalıoğlu',
    name: 'Abalıoğlu Süt Yemi 20 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Dengeli Süt Yemi',
    protein: 20.0,
    starch: 27.0,
    dryMatter: 88.0,
    energyME: 2750,
    cellulose: 8.8,
    calcium: 1.18,
    phosphorus: 0.62,
    approxPrice: 14.35,
    bagWeight: 50,
    description: 'Günlük 25 litre bandındaki sağmallar için süt yağı ve proteinini destekleyen yem.',
  },
  {
    id: 'abalioglu-sut-21',
    brand: 'Abalıoğlu',
    name: 'Abalıoğlu Süt Yemi 21 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim Süt Yemi',
    protein: 21.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2800,
    cellulose: 8.5,
    calcium: 1.25,
    phosphorus: 0.65,
    approxPrice: 15.10,
    bagWeight: 50,
    description: 'Pik süt verimini destekler, süt yağı ve protein kalitesini korur.',
  },
  {
    id: 'abalioglu-sut-22',
    brand: 'Abalıoğlu',
    name: 'Abalıoğlu Süt Yemi 22 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Pik Dönemi Süt Yemi',
    protein: 22.0,
    starch: 28.5,
    dryMatter: 88.0,
    energyME: 2830,
    cellulose: 8.2,
    calcium: 1.28,
    phosphorus: 0.67,
    approxPrice: 15.70,
    bagWeight: 50,
    description: 'Yüksek genetik kapasiteli safkan ırklar için yoğunlaştırılmış protein ve nişasta içeriği.',
  },
  {
    id: 'abalioglu-sampiyon-20',
    brand: 'Abalıoğlu',
    name: 'Abalıoğlu Şampiyon Laktasyon Yemi (20.5 HP)',
    category: 'SUT_YEMI',
    categoryLabel: 'Özel Performans Yemi',
    protein: 20.5,
    starch: 30.0,
    dryMatter: 88.0,
    energyME: 2860,
    cellulose: 7.9,
    calcium: 1.2,
    phosphorus: 0.62,
    approxPrice: 15.80,
    bagWeight: 50,
    description: 'Yoğun tahıl ve bypass yağ içeren formülüyle yüksek verimli ineklerin enerji açığını hızla kapatır.',
  },
  {
    id: 'abalioglu-altin-sut-21',
    brand: 'Abalıoğlu',
    name: 'Abalıoğlu Altın Süt Yemi (21 HP / 2820 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Altın Seri',
    protein: 21.0,
    starch: 28.5,
    dryMatter: 88.0,
    energyME: 2820,
    cellulose: 8.4,
    calcium: 1.22,
    phosphorus: 0.64,
    approxPrice: 15.30,
    bagWeight: 50,
    description: 'Organik çinko, selenyum ve biotin takviyeli tırnak ve meme sağlığı korumalı elit süt yemi.',
  },
  {
    id: 'abalioglu-enerji-sut-18',
    brand: 'Abalıoğlu',
    name: 'Abalıoğlu Enerji Süt Yemi (18 HP / 2850 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Enerji',
    protein: 18.0,
    starch: 30.5,
    dryMatter: 88.0,
    energyME: 2850,
    cellulose: 7.8,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 14.10,
    bagWeight: 50,
    description: 'Mısır ve arpa ağırlıklı enerjisi yoğun, yonca kaba yemi bol olan işletmelere özel yem.',
  },

  // ==========================================
  // MATLI YEM (BURDAN / PROFEED) - TÜM SÜT YEMLERİ
  // ==========================================
  {
    id: 'matli-sut-18',
    brand: 'Matlı',
    name: 'Matlı 18 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Ekonomik Süt Yemi',
    protein: 18.0,
    starch: 25.0,
    dryMatter: 88.0,
    energyME: 2600,
    cellulose: 10.0,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 13.15,
    bagWeight: 50,
    description: 'Matlı kalitesiyle orta verimli ineklerin beslenmesi için ekonomik karma yem.',
  },
  {
    id: 'matli-sut-19',
    brand: 'Matlı',
    name: 'Matlı 19 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 26.5,
    dryMatter: 88.0,
    energyME: 2690,
    cellulose: 9.4,
    calcium: 1.1,
    phosphorus: 0.6,
    approxPrice: 13.75,
    bagWeight: 50,
    description: 'Matlı güvencesiyle üretilmiş, süt ineklerinin günlük ihtiyaçlarını karşılayan standart fabrika süt yemi.',
  },
  {
    id: 'matli-sut-20',
    brand: 'Matlı',
    name: 'Matlı 20 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Dengeli Süt Yemi',
    protein: 20.0,
    starch: 27.2,
    dryMatter: 88.0,
    energyME: 2740,
    cellulose: 8.9,
    calcium: 1.15,
    phosphorus: 0.62,
    approxPrice: 14.45,
    bagWeight: 50,
    description: 'Rumen sindirimini rahatlatan lif-nişasta dengesiyle süt verimini sürdürür.',
  },
  {
    id: 'matli-sut-21',
    brand: 'Matlı',
    name: 'Matlı 21 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim Süt Yemi',
    protein: 21.0,
    starch: 28.0,
    dryMatter: 88.0,
    energyME: 2790,
    cellulose: 8.6,
    calcium: 1.2,
    phosphorus: 0.65,
    approxPrice: 15.10,
    bagWeight: 50,
    description: 'Yüksek süt verimi ve döl verimini desteklemek üzere formule edilmiş zengin proteinli yem.',
  },
  {
    id: 'matli-super-sut-20',
    brand: 'Matlı',
    name: 'Matlı Süper Süt 20 HP / 2800 ME',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Enerji Süt Yemi',
    protein: 20.0,
    starch: 29.5,
    dryMatter: 88.0,
    energyME: 2820,
    cellulose: 8.2,
    calcium: 1.18,
    phosphorus: 0.62,
    approxPrice: 15.30,
    bagWeight: 50,
    description: 'İçerdiği yüksek nişasta ve enerji ile pik süt verimine ulaşmayı kolaylaştırır.',
  },
  {
    id: 'matli-zirve-sut-21',
    brand: 'Matlı',
    name: 'Matlı Zirve Süt 21 HP / 2830 ME',
    category: 'SUT_YEMI',
    categoryLabel: 'Zirve Performans',
    protein: 21.5,
    starch: 29.0,
    dryMatter: 88.0,
    energyME: 2830,
    cellulose: 8.1,
    calcium: 1.25,
    phosphorus: 0.66,
    approxPrice: 15.65,
    bagWeight: 50,
    description: 'Pik süt verimini zirvede tutmak ve döl tutma oranlarını artırmak için tasarlanmış özel yem.',
  },

  // ==========================================
  // OFİS YEM - TÜM SÜT YEMİ ÇEŞİTLERİ
  // ==========================================
  {
    id: 'ofis-klasik-sut-18',
    brand: 'Ofis Yem',
    name: 'Ofis Klasik Süt Yemi 18 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Ekonomik Süt Yemi',
    protein: 18.0,
    starch: 25.0,
    dryMatter: 88.0,
    energyME: 2600,
    cellulose: 10.0,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 13.10,
    bagWeight: 50,
    description: 'Ofis Yem güvencesiyle orta verimli inekler için dengeli ve sindirimi kolay karma yem.',
  },
  {
    id: 'ofis-klasik-sut-19',
    brand: 'Ofis Yem',
    name: 'Ofis Klasik Süt Yemi 19 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2690,
    cellulose: 9.5,
    calcium: 1.1,
    phosphorus: 0.58,
    approxPrice: 13.65,
    bagWeight: 50,
    description: 'Süt verimini destekleyen dengeli enerji, protein ve mineral yapısına sahip standart yem.',
  },
  {
    id: 'ofis-ege-sut-20',
    brand: 'Ofis Yem',
    name: 'Ofis Ege Süt 20 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Bölgesel Özel Seri',
    protein: 20.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2750,
    cellulose: 9.0,
    calcium: 1.15,
    phosphorus: 0.62,
    approxPrice: 14.40,
    bagWeight: 50,
    description: 'Ege ve Marmara bölgesi kaba yemlerine özel optimize edilmiş 20 protein süt yemi.',
  },
  {
    id: 'ofis-master-sut-pelet',
    brand: 'Ofis Yem',
    name: 'Ofis Master Süt Pelet (20 HP / 2850 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Master Performans',
    protein: 20.5,
    starch: 29.5,
    dryMatter: 88.0,
    energyME: 2850,
    cellulose: 8.0,
    calcium: 1.2,
    phosphorus: 0.65,
    approxPrice: 15.50,
    bagWeight: 50,
    description: 'Bitkisel ekstraktlar ve propiyonik asit artırıcı öncüller içeren, süt verimini maksimize eden pelet yem.',
  },
  {
    id: 'ofis-big-top-sut',
    brand: 'Ofis Yem',
    name: 'Ofis Big Top Süt Pelet (21 HP / 2800 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Big Top Yüksek Verim',
    protein: 21.0,
    starch: 28.0,
    dryMatter: 88.0,
    energyME: 2800,
    cellulose: 8.5,
    calcium: 1.25,
    phosphorus: 0.66,
    approxPrice: 15.20,
    bagWeight: 50,
    description: 'Bypass protein ile rumende parçalanabilen proteini mükemmel dengeleyen yüksek verim süt yemi.',
  },
  {
    id: 'ofis-sut-21',
    brand: 'Ofis Yem',
    name: 'Ofis Süt Yemi 21 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim',
    protein: 21.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2780,
    cellulose: 8.8,
    calcium: 1.2,
    phosphorus: 0.63,
    approxPrice: 14.95,
    bagWeight: 50,
    description: 'Yoğun sağım dönemindeki sürülerde kondisyon kaybını önleyen 21 protein formülü.',
  },

  // ==========================================
  // ÇAMLI YEM (YAŞAR HOLDİNG) - TÜM SÜT YEMLERİ
  // ==========================================
  {
    id: 'camli-standart-sut-18',
    brand: 'Çamlı Yem',
    name: 'Çamlı Standart Süt 18 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Ekonomik Süt Yemi',
    protein: 18.0,
    starch: 25.0,
    dryMatter: 88.0,
    energyME: 2600,
    cellulose: 10.0,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 13.20,
    bagWeight: 50,
    description: 'Çamlı kalitesiyle orta verimli ineklerin beslenmesinde ekonomik çözüm.',
  },
  {
    id: 'camli-bio-sut-19',
    brand: 'Çamlı Yem',
    name: 'Çamlı Bio Süt Yemi 19 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Bio Teknoloji Serisi',
    protein: 19.0,
    starch: 26.2,
    dryMatter: 88.0,
    energyME: 2700,
    cellulose: 9.3,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 13.80,
    bagWeight: 50,
    description: 'Sindirim sistemi florasını destekleyen probiyotik ve maya türevleri içeren dengeli yem.',
  },
  {
    id: 'camli-laktasyon-20',
    brand: 'Çamlı Yem',
    name: 'Çamlı Laktasyon Süt 20 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Dengeli Laktasyon',
    protein: 20.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2760,
    cellulose: 8.8,
    calcium: 1.2,
    phosphorus: 0.62,
    approxPrice: 14.50,
    bagWeight: 50,
    description: 'Laktasyonun tepe noktasında süt verimini ve kalitesini korur.',
  },
  {
    id: 'camli-bio-sut-21',
    brand: 'Çamlı Yem',
    name: 'Çamlı Bio Süt Yemi 21 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Bio Yüksek Verim',
    protein: 21.0,
    starch: 28.0,
    dryMatter: 88.0,
    energyME: 2800,
    cellulose: 8.4,
    calcium: 1.25,
    phosphorus: 0.65,
    approxPrice: 15.25,
    bagWeight: 50,
    description: 'Yüksek süt verimi ve döl verimini destekleyen bypass proteinli formül.',
  },
  {
    id: 'camli-pik-laktasyon-22',
    brand: 'Çamlı Yem',
    name: 'Çamlı Pik Laktasyon 22 HP (2850 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Pik Zirve Serisi',
    protein: 22.0,
    starch: 29.5,
    dryMatter: 88.0,
    energyME: 2850,
    cellulose: 7.9,
    calcium: 1.3,
    phosphorus: 0.68,
    approxPrice: 16.20,
    bagWeight: 50,
    description: '32 litre üstü elit sağmallarda ketozisi önleyen yüksek enerjili ve nişastalı zirve yemi.',
  },

  // ==========================================
  // TOROS YEM - TÜM SÜT YEMİ ÇEŞİTLERİ
  // ==========================================
  {
    id: 'toros-sut-18',
    brand: 'Toros Yem',
    name: 'Toros 18 HP Süt Yemi (2600 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Ekonomik Süt Yemi',
    protein: 18.0,
    starch: 25.0,
    dryMatter: 88.0,
    energyME: 2600,
    cellulose: 10.0,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 13.00,
    bagWeight: 50,
    description: 'Laktasyon sonundaki hayvanların kondisyonunu düzeltirken ekonomik süt üretimi sağlar.',
  },
  {
    id: 'toros-sut-19',
    brand: 'Toros Yem',
    name: 'Toros 19 HP Süt Yemi (2680 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2680,
    cellulose: 9.6,
    calcium: 1.1,
    phosphorus: 0.58,
    approxPrice: 13.50,
    bagWeight: 50,
    description: 'Akdeniz ve İç Anadolu rasyonlarına uygun, lezzetli ve yüksek tüketilebilirlikli süt yemi.',
  },
  {
    id: 'toros-sut-20',
    brand: 'Toros Yem',
    name: 'Toros 20 HP Süt Yemi (2740 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Dengeli Süt Yemi',
    protein: 20.0,
    starch: 27.0,
    dryMatter: 88.0,
    energyME: 2740,
    cellulose: 9.1,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 14.20,
    bagWeight: 50,
    description: 'Orta-yüksek verimli sağmallarda süt verimini dengede tutan formülasyon.',
  },
  {
    id: 'toros-sut-21',
    brand: 'Toros Yem',
    name: 'Toros 21 HP Süt Yemi (2780 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim Süt Yemi',
    protein: 21.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2780,
    cellulose: 8.8,
    calcium: 1.2,
    phosphorus: 0.62,
    approxPrice: 14.90,
    bagWeight: 50,
    description: '25-30 kg üzeri süt verimlerinde protein ihtiyacını eksiksiz karşılayan konsantre formülasyon.',
  },
  {
    id: 'toros-sut-22',
    brand: 'Toros Yem',
    name: 'Toros 22 HP Süt Yemi (2820 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Pik Laktasyon',
    protein: 22.0,
    starch: 28.5,
    dryMatter: 88.0,
    energyME: 2820,
    cellulose: 8.3,
    calcium: 1.25,
    phosphorus: 0.65,
    approxPrice: 15.50,
    bagWeight: 50,
    description: 'Pik dönemindeki ineklerde süt yağı ve proteinini koruyan elit yem.',
  },
  {
    id: 'toros-zirve-sut-20',
    brand: 'Toros Yem',
    name: 'Toros Zirve Süt Yemi (20 HP / 2820 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Zirve Serisi',
    protein: 20.0,
    starch: 29.0,
    dryMatter: 88.0,
    energyME: 2820,
    cellulose: 8.0,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 15.20,
    bagWeight: 50,
    description: 'Yüksek nişasta ve sindirilebilir lif ile süt veriminde zirveye ulaşmayı hedefler.',
  },
  {
    id: 'toros-enerji-sut-18',
    brand: 'Toros Yem',
    name: 'Toros Enerji Süt Yemi (18 HP / 2800 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Enerji',
    protein: 18.0,
    starch: 30.0,
    dryMatter: 88.0,
    energyME: 2800,
    cellulose: 8.0,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 14.00,
    bagWeight: 50,
    description: 'Bol yoncalı işletmelerde negatif enerji dengesini kapatan yüksek nişastalı süt yemi.',
  },

  // ==========================================
  // ERİŞ YEM - TÜM SÜT YEMİ ÇEŞİTLERİ
  // ==========================================
  {
    id: 'eris-eko-sut-18',
    brand: 'Eriş Yem',
    name: 'Eriş Eko Süt Yemi 18 HP',
    category: 'SUT_YEMI',
    categoryLabel: 'Ekonomik Süt Yemi',
    protein: 18.0,
    starch: 25.0,
    dryMatter: 88.0,
    energyME: 2600,
    cellulose: 10.0,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 13.00,
    bagWeight: 50,
    description: 'Eriş Yem güvencesiyle orta verimli inekler için ekonomik formülasyon.',
  },
  {
    id: 'eris-sut-19',
    brand: 'Eriş Yem',
    name: 'Eriş 19 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2690,
    cellulose: 9.5,
    calcium: 1.1,
    phosphorus: 0.6,
    approxPrice: 13.60,
    bagWeight: 50,
    description: 'Marmara ve Ege bölgesinde yaygın kullanılan, homojen pelet yapısıyla yüksek tüketim sağlayan yem.',
  },
  {
    id: 'eris-sut-20',
    brand: 'Eriş Yem',
    name: 'Eriş 20 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Dengeli Süt Yemi',
    protein: 20.0,
    starch: 27.0,
    dryMatter: 88.0,
    energyME: 2740,
    cellulose: 9.0,
    calcium: 1.18,
    phosphorus: 0.62,
    approxPrice: 14.30,
    bagWeight: 50,
    description: 'Süt verimini destekleyen dengeli lif ve nişasta oranı.',
  },
  {
    id: 'eris-sut-21',
    brand: 'Eriş Yem',
    name: 'Eriş 21 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim Süt Yemi',
    protein: 21.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2790,
    cellulose: 8.7,
    calcium: 1.22,
    phosphorus: 0.64,
    approxPrice: 15.00,
    bagWeight: 50,
    description: 'Laktasyonun ilk 100 gününde yüksek protein desteği sağlayarak kondisyonu korur.',
  },
  {
    id: 'eris-pik-sut-22',
    brand: 'Eriş Yem',
    name: 'Eriş Pik Süt Yemi (22 HP / 2840 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Pik Dönemi',
    protein: 22.0,
    starch: 29.5,
    dryMatter: 88.0,
    energyME: 2840,
    cellulose: 8.0,
    calcium: 1.25,
    phosphorus: 0.66,
    approxPrice: 15.70,
    bagWeight: 50,
    description: 'Erken laktasyondaki yüksek genetikli ineklerin enerji açığını kapatır.',
  },

  // ==========================================
  // ÖZLEM YEM - TÜM SÜT YEMİ ÇEŞİTLERİ
  // ==========================================
  {
    id: 'ozlem-sut-18',
    brand: 'Özlem Yem',
    name: 'Özlem 18 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Ekonomik Süt Yemi',
    protein: 18.0,
    starch: 25.0,
    dryMatter: 88.0,
    energyME: 2600,
    cellulose: 10.2,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 13.00,
    bagWeight: 50,
    description: 'Laktasyon sonu ve düşük verimli hayvanlar için güvenli karma yem.',
  },
  {
    id: 'ozlem-sut-19',
    brand: 'Özlem Yem',
    name: 'Özlem 19 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 25.5,
    dryMatter: 88.0,
    energyME: 2680,
    cellulose: 9.8,
    calcium: 1.1,
    phosphorus: 0.58,
    approxPrice: 13.50,
    bagWeight: 50,
    description: 'Sindirim dengesini koruyan ve asidoz riskini azaltan dengeli tahıl ve küspe karışımı.',
  },
  {
    id: 'ozlem-sut-20',
    brand: 'Özlem Yem',
    name: 'Özlem 20 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Dengeli Süt Yemi',
    protein: 20.0,
    starch: 26.5,
    dryMatter: 88.0,
    energyME: 2730,
    cellulose: 9.3,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 14.20,
    bagWeight: 50,
    description: 'Rumen ortamını asitlendirmeden optimum süt verimi sağlayan özel formül.',
  },
  {
    id: 'ozlem-sut-21',
    brand: 'Özlem Yem',
    name: 'Özlem 21 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim Süt Yemi',
    protein: 21.0,
    starch: 27.0,
    dryMatter: 88.0,
    energyME: 2770,
    cellulose: 9.0,
    calcium: 1.2,
    phosphorus: 0.62,
    approxPrice: 14.85,
    bagWeight: 50,
    description: 'Yüksek kaliteli soya ve kanola küspesiyle güçlendirilmiş 21 protein formülü.',
  },
  {
    id: 'ozlem-gurme-sut-20',
    brand: 'Özlem Yem',
    name: 'Özlem Gurme Süt Yemi (20 HP / 2800 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Gurme Özel Seri',
    protein: 20.0,
    starch: 28.5,
    dryMatter: 88.0,
    energyME: 2800,
    cellulose: 8.5,
    calcium: 1.18,
    phosphorus: 0.62,
    approxPrice: 15.10,
    bagWeight: 50,
    description: 'Yüksek tüketim ve lezzetlilik sağlayan melas ve özel aroma katkılı Gurme serisi.',
  },
  {
    id: 'ozlem-enerji-sut-18',
    brand: 'Özlem Yem',
    name: 'Özlem Enerji Süt Yemi (18 HP / 2820 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Enerji',
    protein: 18.0,
    starch: 30.0,
    dryMatter: 88.0,
    energyME: 2820,
    cellulose: 8.0,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 14.00,
    bagWeight: 50,
    description: 'Kaba yemi yonca ve fiğ olan işletmelerde enerji dengesini sağlayan yüksek tahıllı yem.',
  },

  // ==========================================
  // TRAKYA BİRLİK YEM - TÜM SÜT YEMLERİ
  // ==========================================
  {
    id: 'trakyabirlik-sut-18',
    brand: 'Trakya Birlik',
    name: 'Trakya Birlik 18 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Ekonomik Süt Yemi',
    protein: 18.0,
    starch: 24.5,
    dryMatter: 88.0,
    energyME: 2600,
    cellulose: 10.5,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 12.90,
    bagWeight: 50,
    description: 'Trakya kooperatif üreticileri için ayçiçeği küspesi ve kepek dengeli ekonomik süt yemi.',
  },
  {
    id: 'trakyabirlik-sut-19',
    brand: 'Trakya Birlik',
    name: 'Trakya Birlik 19 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 25.0,
    dryMatter: 88.0,
    energyME: 2650,
    cellulose: 10.0,
    calcium: 1.1,
    phosphorus: 0.58,
    approxPrice: 13.40,
    bagWeight: 50,
    description: 'Trakya Birlik kooperatifi güvencesiyle üretilen, ayçiçeği küspesi ve hububat ağırlıklı güvenilir yem.',
  },
  {
    id: 'trakyabirlik-sut-20',
    brand: 'Trakya Birlik',
    name: 'Trakya Birlik 20 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Dengeli Süt Yemi',
    protein: 20.0,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2700,
    cellulose: 9.5,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 14.10,
    bagWeight: 50,
    description: 'Süt verimini koruyan ve döl verimini destekleyen Trakya Birlik yem.',
  },
  {
    id: 'trakyabirlik-sut-21',
    brand: 'Trakya Birlik',
    name: 'Trakya Birlik 21 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim Süt Yemi',
    protein: 21.0,
    starch: 26.5,
    dryMatter: 88.0,
    energyME: 2750,
    cellulose: 9.2,
    calcium: 1.2,
    phosphorus: 0.62,
    approxPrice: 14.80,
    bagWeight: 50,
    description: 'Protein yoğunluğu artırılmış, kooperatif üreticileri için optimize edilmiş süt yemi.',
  },
  {
    id: 'trakyabirlik-ozel-sut-21',
    brand: 'Trakya Birlik',
    name: 'Trakya Birlik Özel Süt Yemi (21 HP / 2800 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Özel Seri Süt Yemi',
    protein: 21.0,
    starch: 28.0,
    dryMatter: 88.0,
    energyME: 2800,
    cellulose: 8.6,
    calcium: 1.22,
    phosphorus: 0.64,
    approxPrice: 15.20,
    bagWeight: 50,
    description: 'Yüksek enerjili mısır ve soya takviyeli özel laktasyon rasyonu.',
  },

  // ==========================================
  // PEHLİVAN YEM - TÜM SÜT YEMLERİ
  // ==========================================
  {
    id: 'pehlivan-sut-18',
    brand: 'Pehlivan Yem',
    name: 'Pehlivan 18 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Ekonomik Süt Yemi',
    protein: 18.0,
    starch: 25.0,
    dryMatter: 88.0,
    energyME: 2600,
    cellulose: 10.0,
    calcium: 1.05,
    phosphorus: 0.55,
    approxPrice: 13.00,
    bagWeight: 50,
    description: 'Trakya ve Marmara yetiştiricileri için ekonomik pelet süt yemi.',
  },
  {
    id: 'pehlivan-sut-19',
    brand: 'Pehlivan Yem',
    name: 'Pehlivan 19 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2680,
    cellulose: 9.6,
    calcium: 1.1,
    phosphorus: 0.58,
    approxPrice: 13.55,
    bagWeight: 50,
    description: 'Pehlivan Yem güvencesiyle standart süt verimini sürdüren dengeli karma.',
  },
  {
    id: 'pehlivan-sut-20',
    brand: 'Pehlivan Yem',
    name: 'Pehlivan 20 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Dengeli Süt Yemi',
    protein: 20.0,
    starch: 27.0,
    dryMatter: 88.0,
    energyME: 2740,
    cellulose: 9.0,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 14.25,
    bagWeight: 50,
    description: 'Süt pikini destekleyen ve kondisyon koruyan 20 protein yem.',
  },
  {
    id: 'pehlivan-sut-21',
    brand: 'Pehlivan Yem',
    name: 'Pehlivan 21 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim Süt Yemi',
    protein: 21.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2780,
    cellulose: 8.8,
    calcium: 1.2,
    phosphorus: 0.62,
    approxPrice: 14.90,
    bagWeight: 50,
    description: 'Yüksek verimli sürüler için kaliteli protein ve nişasta kaynağı.',
  },
  {
    id: 'pehlivan-sampiyon-21',
    brand: 'Pehlivan Yem',
    name: 'Pehlivan Şampiyon Süt (21 HP / 2820 ME)',
    category: 'SUT_YEMI',
    categoryLabel: 'Şampiyon Performans',
    protein: 21.0,
    starch: 28.5,
    dryMatter: 88.0,
    energyME: 2820,
    cellulose: 8.3,
    calcium: 1.25,
    phosphorus: 0.65,
    approxPrice: 15.35,
    bagWeight: 50,
    description: 'Pik süt verimini uzatmak için ekstra enerji ve mineral takviyeli özel yem.',
  },

  // ==========================================
  // ŞENPİLİÇ YEM & HEKİMOĞLU YEM
  // ==========================================
  {
    id: 'senpilic-sut-19',
    brand: 'Şenpiliç Yem',
    name: 'Şenpiliç 19 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2680,
    cellulose: 9.5,
    calcium: 1.1,
    phosphorus: 0.58,
    approxPrice: 13.50,
    bagWeight: 50,
    description: 'Şenpiliç tesislerinde son teknolojiyle üretilen dengeli süt yemi.',
  },
  {
    id: 'senpilic-sut-21',
    brand: 'Şenpiliç Yem',
    name: 'Şenpiliç 21 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim Süt Yemi',
    protein: 21.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2780,
    cellulose: 8.7,
    calcium: 1.2,
    phosphorus: 0.62,
    approxPrice: 14.85,
    bagWeight: 50,
    description: 'Yüksek laktasyon verimini destekleyen zengin proteinli yem.',
  },
  {
    id: 'hekimoglu-sut-19',
    brand: 'Hekimoğlu',
    name: 'Hekimoğlu 19 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Standart Süt Yemi',
    protein: 19.0,
    starch: 26.0,
    dryMatter: 88.0,
    energyME: 2680,
    cellulose: 9.5,
    calcium: 1.1,
    phosphorus: 0.58,
    approxPrice: 13.50,
    bagWeight: 50,
    description: 'Orta Anadolu koşullarına uygun, buğday ve arpa bazlı süt yemi.',
  },
  {
    id: 'hekimoglu-sut-21',
    brand: 'Hekimoğlu',
    name: 'Hekimoğlu 21 Süt Yemi',
    category: 'SUT_YEMI',
    categoryLabel: 'Yüksek Verim Süt Yemi',
    protein: 21.0,
    starch: 27.5,
    dryMatter: 88.0,
    energyME: 2780,
    cellulose: 8.8,
    calcium: 1.2,
    phosphorus: 0.62,
    approxPrice: 14.80,
    bagWeight: 50,
    description: 'Yüksek verimli süt ineklerinde erken laktasyon protein desteği.',
  },

  // ==========================================
  // DÜVE & KURU DÖNEM GEÇİŞ YEMLERİ
  // ==========================================
  {
    id: 'proyem-kuru-donem',
    brand: 'Proyem',
    name: 'Proyem Kuru Dönem Yemi (15 HP)',
    category: 'KURU_DONEM',
    categoryLabel: 'Kuru Dönem & Geçiş',
    protein: 15.0,
    starch: 20.0,
    dryMatter: 88.0,
    energyME: 2450,
    cellulose: 12.0,
    calcium: 0.6,
    phosphorus: 0.5,
    approxPrice: 12.80,
    bagWeight: 50,
    description: 'Doğuma 60-21 gün kala kullanılan, hipokalsemi (süt humması) riskini önlemek için düşük kalsiyumlu formül.',
  },
  {
    id: 'cp-kuru-donem',
    brand: 'CP Yem',
    name: 'CP Kuru Dönem Yemi (15 HP)',
    category: 'KURU_DONEM',
    categoryLabel: 'Kuru Dönem',
    protein: 15.0,
    starch: 21.0,
    dryMatter: 88.0,
    energyME: 2480,
    cellulose: 11.5,
    calcium: 0.6,
    phosphorus: 0.5,
    approxPrice: 12.90,
    bagWeight: 50,
    description: 'Doğuma hazırlık sürecinde fötus gelişimini destekler ve yağlanmayı önler.',
  },
  {
    id: 'matli-dogum-oncesi',
    brand: 'Matlı',
    name: 'Matlı Doğum Öncesi Hazırlık Yemi (16 HP)',
    category: 'KURU_DONEM',
    categoryLabel: 'Doğum Öncesi Hazırlık',
    protein: 16.0,
    starch: 22.0,
    dryMatter: 88.0,
    energyME: 2520,
    cellulose: 11.0,
    calcium: 0.65,
    phosphorus: 0.52,
    approxPrice: 13.20,
    bagWeight: 50,
    description: 'Doğuma 21 gün kala işkembe papillalarını süt yemine adapte eden geçiş yemi.',
  },
  {
    id: 'tkyem-kuru-donem',
    brand: 'Tarım Kredi',
    name: 'Tarım Kredi Kuru Dönem Yemi (15 HP)',
    category: 'KURU_DONEM',
    categoryLabel: 'Kuru Dönem',
    protein: 15.0,
    starch: 20.5,
    dryMatter: 88.0,
    energyME: 2460,
    cellulose: 11.8,
    calcium: 0.6,
    phosphorus: 0.5,
    approxPrice: 12.80,
    bagWeight: 50,
    description: 'Kuru dönemdeki ineğin mineral dengesini ayarlayarak doğum felcini önler.',
  },
  {
    id: 'cp-duve-yemi',
    brand: 'CP Yem',
    name: 'CP Düve Geliştirme Yemi (16 HP)',
    category: 'DUVE_BUZAGI',
    categoryLabel: 'Düve Geliştirme',
    protein: 16.0,
    starch: 24.0,
    dryMatter: 88.0,
    energyME: 2550,
    cellulose: 11.0,
    calcium: 1.1,
    phosphorus: 0.6,
    approxPrice: 13.00,
    bagWeight: 50,
    description: 'İlk tohumlama yaşına kadar düvelerin iskelet gelişimini destekler, yağlanmayı engeller.',
  },
  {
    id: 'proyem-duve-yemi',
    brand: 'Proyem',
    name: 'Proyem Düve Yemi (16 HP)',
    category: 'DUVE_BUZAGI',
    categoryLabel: 'Düve Geliştirme',
    protein: 16.0,
    starch: 24.5,
    dryMatter: 88.0,
    energyME: 2560,
    cellulose: 10.8,
    calcium: 1.15,
    phosphorus: 0.6,
    approxPrice: 13.10,
    bagWeight: 50,
    description: 'Döl verimi yüksek, çatısı geniş sağlıklı damızlık düve yetiştirmek için dengeli büyüme yemi.',
  }
];
