import { FeedCategory } from '@/types';

export interface RoughageQualityOption {
  qualityGrade: '1_SINIF' | '2_SINIF';
  qualityLabel: string;        // Örn: "1. Sınıf (Normal / Yüksek Kalite)" veya "2. Sınıf (Orta Kalite / Geç Hasat)"
  badgeColor: string;          // emerald veya amber
  dryMatter: number;           // % Kuru Madde
  protein: number;             // % Ham Protein (KM üzerinden)
  starch: number;              // % Nişasta (KM üzerinden)
  maxLimitKg: number;          // Tavsiye edilen üst sınır (taze kg)
  approxPriceTL: number;       // Yaklaşık referans kg fiyatı (TL/kg)
  fieldDescription: string;    // Çiftlikte ayırt etme rehberi (görünüm, koku, yapı)
}

export interface RoughageReferenceFeed {
  id: string;
  name: string;                // Yem adı (örn: "Yonca Kuru Otu")
  feedType?: 'KABA' | 'KESIF'; // Varsayılan KABA, hububatlar için KESIF
  category: FeedCategory;
  categoryLabel: string;
  icon: string;                // '🌿', '🌽', '🌾', '🌱', '🍯'
  generalInfo: string;         // Besleme genel bilgi
  qualities: {
    firstGrade: RoughageQualityOption;
    secondGrade: RoughageQualityOption;
  };
}

export const ROUGHAGE_REFERENCE_CATALOG: RoughageReferenceFeed[] = [
  {
    id: 'yonca-kuru-otu',
    name: 'Yonca Kuru Otu',
    category: 'KURU_OT',
    categoryLabel: 'Kuru Ot',
    icon: '🌿',
    generalInfo: 'Süt sığırcılığının kraliçesi. Yüksek kalsiyum, sindirilebilir lif ve kaliteli ham protein sağlar.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Bol Yapraklı)',
        badgeColor: 'emerald',
        dryMatter: 88.0,
        protein: 18.0,
        starch: 2.5,
        maxLimitKg: 6.0,
        approxPriceTL: 8.50,
        fieldDescription: 'Mor çiçeklenme başlangıcında (%10 çiçek) biçilmiş, gövdesi ince, yaprakları dökülmemiş, parlak yeşil ve mis kokulu.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Saplı)',
        badgeColor: 'amber',
        dryMatter: 86.0,
        protein: 14.0,
        starch: 2.0,
        maxLimitKg: 5.0,
        approxPriceTL: 6.50,
        fieldDescription: 'Geç biçilmiş (tam çiçeklenme veya tohum tutmuş), kalın ve sert saplı, yapraklarının bir kısmı dökülmüş, sarımtırak-yeşil.',
      },
    },
  },
  {
    id: 'misir-silaji',
    name: 'Mısır Silajı',
    category: 'SILAJ',
    categoryLabel: 'Silaj',
    icon: '🌽',
    generalInfo: 'Enerji ve nişastanın ana kaba yem kaynağı. Süt verimini ve kuru madde tüketimini yukarı çeker.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Bol Taneli & İdeal Fermantasyon)',
        badgeColor: 'emerald',
        dryMatter: 33.0,
        protein: 8.5,
        starch: 32.0,
        maxLimitKg: 25.0,
        approxPriceTL: 3.20,
        fieldDescription: 'Tane oranı yüksek (koçanlı), süt çizgisi 1/2 seviyesinde hasat edilmiş, hoş fermente ekşimsi kokulu, küfsüz, altın sarısı-yeşil.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Sulu veya Düşük Taneli)',
        badgeColor: 'amber',
        dryMatter: 27.0,
        protein: 7.0,
        starch: 22.0,
        maxLimitKg: 20.0,
        approxPriceTL: 2.50,
        fieldDescription: 'Erken hasat edilmiş (fazla sulu, sıkıldığında su damlar) veya koçan/tane tutumu zayıf, aşırı asidik veya geç kalmış kuru silaj.',
      },
    },
  },
  {
    id: 'seker-pancari-posasi',
    name: 'Şeker Pancarı Posası (Yaş Küspe)',
    category: 'YAS_KUSPE',
    categoryLabel: 'Yaş Küspe & Sulu Kaba Yem',
    icon: '🍯',
    generalInfo: 'Yüksek pektin lifi ve lezzetiyle işkembe dostu kaba yem. Asidoz yapmadan enerji verir ve süt yağını artırır.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / İyi Preslenmiş & Taze Paket)',
        badgeColor: 'emerald',
        dryMatter: 22.0,
        protein: 9.5,
        starch: 2.0,
        maxLimitKg: 15.0,
        approxPriceTL: 1.80,
        fieldDescription: 'Fabrikadan iyi preslenmiş, vakumlu rulo pakette bozulmadan fermente olmuş, açık gri-kahverengi, ekşi maya kokulu.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Sulu & Açıkta Beklemiş)',
        badgeColor: 'amber',
        dryMatter: 16.0,
        protein: 7.5,
        starch: 1.5,
        maxLimitKg: 12.0,
        approxPriceTL: 1.20,
        fieldDescription: 'Preslenmemiş sulu havuz küspesi veya açıkta beklediği için nemi yüksek, hafif kararmış (ancak küflenmemiş) küspe.',
      },
    },
  },
  {
    id: 'bugday-samani',
    name: 'Buğday Samanı',
    category: 'SAMAN',
    categoryLabel: 'Saman',
    icon: '🌾',
    generalInfo: 'İşkembede mekanik geviş getirmeyi tetikleyen ve rumen matı (fiber mat) oluşturan temel yapısal lif kaynağı.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Temiz & Altın Sarısı)',
        badgeColor: 'emerald',
        dryMatter: 90.0,
        protein: 3.5,
        starch: 1.5,
        maxLimitKg: 3.5,
        approxPriceTL: 3.00,
        fieldDescription: 'Patozda çok toz edilmemiş (3-5 cm kıyım), yağmur yememiş, küfsüz, tozsuz, parlak altın sarısı.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Esmer veya Tozlu)',
        badgeColor: 'amber',
        dryMatter: 88.0,
        protein: 2.5,
        starch: 1.0,
        maxLimitKg: 2.5,
        approxPriceTL: 2.20,
        fieldDescription: 'Tarlada yağmur yemiş, rengi matlaşmış veya aşırı un gibi ufalanmış, besin değeri zayıf saman.',
      },
    },
  },
  {
    id: 'arpa-samani',
    name: 'Arpa Samanı',
    category: 'SAMAN',
    categoryLabel: 'Saman',
    icon: '🌾',
    generalInfo: 'Buğday samanına göre daha yumuşak dokulu ve inekler tarafından daha iştahla tüketilen saman türü.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Yumuşak & Parlak)',
        badgeColor: 'emerald',
        dryMatter: 89.0,
        protein: 4.0,
        starch: 2.0,
        maxLimitKg: 4.0,
        approxPriceTL: 3.20,
        fieldDescription: 'Açık sarı, temiz, küfsüz, yaprak oranı iyi ve ineklerin kolay geviş getirdiği yumuşak saplar.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Kararmış)',
        badgeColor: 'amber',
        dryMatter: 87.0,
        protein: 2.8,
        starch: 1.2,
        maxLimitKg: 3.0,
        approxPriceTL: 2.40,
        fieldDescription: 'Tarlada beklemiş, rengi koyulaşmış veya nem almış orta kalite arpa samanı.',
      },
    },
  },
  {
    id: 'fig-kuru-otu',
    name: 'Fiğ Kuru Otu',
    category: 'KURU_OT',
    categoryLabel: 'Kuru Ot',
    icon: '🌱',
    generalInfo: 'Baklagil kaba yemi. Yoncaya en yakın yüksek proteinli ve lezzetli yerli kuru ot alternatifi.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Erken Biçim & Bol Yaprak)',
        badgeColor: 'emerald',
        dryMatter: 88.0,
        protein: 16.0,
        starch: 2.5,
        maxLimitKg: 5.0,
        approxPriceTL: 7.00,
        fieldDescription: 'Alt baklalar dolmadan önce biçilmiş, yaprakları dökülmemiş, yeşilimsi renkli ve yumuşak.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Tohuma Kaçmış)',
        badgeColor: 'amber',
        dryMatter: 86.0,
        protein: 12.0,
        starch: 2.0,
        maxLimitKg: 4.0,
        approxPriceTL: 5.20,
        fieldDescription: 'Tohum bağladıktan sonra geç biçilmiş, sapları odunlaşmış ve yaprak kaybı fazla.',
      },
    },
  },
  {
    id: 'korunga-kuru-otu',
    name: 'Korunga Kuru Otu',
    category: 'KURU_OT',
    categoryLabel: 'Kuru Ot',
    icon: '🌸',
    generalInfo: 'Şişkinlik yapmayan (tanen içeren) mucizevi baklagil. Sindirim sistemini korur, protein sağlar.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Pembe Çiçeklenme Dönemi)',
        badgeColor: 'emerald',
        dryMatter: 88.0,
        protein: 15.5,
        starch: 2.5,
        maxLimitKg: 5.5,
        approxPriceTL: 7.20,
        fieldDescription: 'Pembe çiçek açma başlangıcında biçilmiş, yaprak ve çiçek oranı yüksek, yeşil-pembe tonlarında.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Geç Biçim)',
        badgeColor: 'amber',
        dryMatter: 86.0,
        protein: 11.5,
        starch: 2.0,
        maxLimitKg: 4.5,
        approxPriceTL: 5.50,
        fieldDescription: 'Çiçekleri geçmiş, tohum bağlamış ve sapları sertleşmiş orta kalite korunga otu.',
      },
    },
  },
  {
    id: 'cayir-otu',
    name: 'Çayır Otu / Kuru Ot',
    category: 'KURU_OT',
    categoryLabel: 'Kuru Ot',
    icon: '🌾',
    generalInfo: 'Doğal meralardan ve çayırlardan biçilen çoklu buğdaygil-baklagil karışımı dengeli kaba yem.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Bahar Biçimi Dağ Çayırı)',
        badgeColor: 'emerald',
        dryMatter: 88.0,
        protein: 11.5,
        starch: 3.0,
        maxLimitKg: 6.0,
        approxPriceTL: 5.50,
        fieldDescription: 'Başaklanma öncesi erken dönemde biçilmiş, yabancı dikensiz, bol yapraklı ve yeşilimsi.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Geç Yaz Biçimi)',
        badgeColor: 'amber',
        dryMatter: 85.0,
        protein: 7.5,
        starch: 2.0,
        maxLimitKg: 5.0,
        approxPriceTL: 4.00,
        fieldDescription: 'Geç kalmış, sararmış, sert başaklı ve selüloz oranı yüksek kuru ot.',
      },
    },
  },
  {
    id: 'yulaf-kuru-otu',
    name: 'Yulaf Kuru Otu (Yeşil Yulaf Otu)',
    category: 'KURU_OT',
    categoryLabel: 'Kuru Ot',
    icon: '🌾',
    generalInfo: 'Süt olum devresinde biçildiğinde hem tatlı nişasta hem de sindirilebilir lif sağlayan lezzetli yem.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Süt-Hamur Olum Hasadı)',
        badgeColor: 'emerald',
        dryMatter: 88.0,
        protein: 9.5,
        starch: 5.0,
        maxLimitKg: 6.0,
        approxPriceTL: 5.20,
        fieldDescription: 'Daneler süt olumundayken biçilmiş, yaprakları yeşil, daneleri ezildiğinde süt kıvamında, iştah açıcı.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Sarı Olum veya Yağmurlu)',
        badgeColor: 'amber',
        dryMatter: 86.0,
        protein: 7.0,
        starch: 3.0,
        maxLimitKg: 5.0,
        approxPriceTL: 3.80,
        fieldDescription: 'Geç biçildiği için daneleri dökülmüş veya samana yaklaşmış sert saplı ot.',
      },
    },
  },
  {
    id: 'reygras-kuru-otu',
    name: 'İtalyan Çimi (Reygras) Kuru Otu',
    category: 'KURU_OT',
    categoryLabel: 'Kuru Ot',
    icon: '🌱',
    generalInfo: 'Tek yıllık süt otu. Şeker ve enerji oranı yüksek, sindirimi son derece kolay modern kaba yem.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Kardeşlenme Sonu Biçim)',
        badgeColor: 'emerald',
        dryMatter: 87.0,
        protein: 14.5,
        starch: 3.5,
        maxLimitKg: 6.0,
        approxPriceTL: 6.80,
        fieldDescription: 'Başak çıkarmadan önce biçilmiş, ince ve yumuşak saplı, parlak yeşil ve şekerli kokuya sahip.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Başaklanmış)',
        badgeColor: 'amber',
        dryMatter: 85.0,
        protein: 10.0,
        starch: 2.2,
        maxLimitKg: 5.0,
        approxPriceTL: 5.00,
        fieldDescription: 'Başak çıkardıktan sonra biçilmiş, sapları liflenip sertleşmiş reygras otu.',
      },
    },
  },
  {
    id: 'reygras-silaji',
    name: 'Reygras / Ot Silajı (Süt Otu Silajı)',
    category: 'SILAJ',
    categoryLabel: 'Silaj',
    icon: '🌱',
    generalInfo: 'Yüksek proteinli ve lezzetli rulo/paket ot silajı. Yonca kuru otu yerine rasyona mükemmel uyum sağlar.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Soldurulmuş & İdeal Fermantasyon)',
        badgeColor: 'emerald',
        dryMatter: 38.0,
        protein: 14.0,
        starch: 4.0,
        maxLimitKg: 15.0,
        approxPriceTL: 3.50,
        fieldDescription: 'Tarlada 1 gün soldurulduktan sonra paketlenmiş (%35-40 KM), zeytin yeşili, mis gibi turşu kokulu.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Fazla Yaş veya Geç Biçim)',
        badgeColor: 'amber',
        dryMatter: 28.0,
        protein: 10.0,
        starch: 2.5,
        maxLimitKg: 12.0,
        approxPriceTL: 2.70,
        fieldDescription: 'Soldurulmadan direkt paketlenmiş (aşırı sulu) veya başaklandıktan sonra sarılmış ot silajı.',
      },
    },
  },
  {
    id: 'arpa-silaji',
    name: 'Arpa Silajı (Yeşil Hububat Silajı)',
    category: 'SILAJ',
    categoryLabel: 'Silaj',
    icon: '🌾',
    generalInfo: 'Mısır silajının yetişmediği veya erken hasat gereken bölgelerde mükemmel bir kışlık silaj alternatifi.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Hamur Olum Devresi)',
        badgeColor: 'emerald',
        dryMatter: 35.0,
        protein: 10.5,
        starch: 18.0,
        maxLimitKg: 18.0,
        approxPriceTL: 3.00,
        fieldDescription: 'Daneleri hamur olumundayken biçilip iyi sıkıştırılmış, açık zeytin yeşili ve hoş kokulu.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Sarı Olum veya Sulu)',
        badgeColor: 'amber',
        dryMatter: 28.0,
        protein: 8.0,
        starch: 12.0,
        maxLimitKg: 14.0,
        approxPriceTL: 2.30,
        fieldDescription: 'Kılçıkları sertleştikten sonra biçilmiş veya erken biçilip sulu kalmış silaj.',
      },
    },
  },
  {
    id: 'sorgum-silaji',
    name: 'Sorgum-Sudan Otu Silajı',
    category: 'SILAJ',
    categoryLabel: 'Silaj',
    icon: '🎋',
    generalInfo: 'Kuraklığa dayanıklı, sulama imkanı kısıtlı bölgelerin yüksek verimli alternatif silaj kaynağı.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Süt-Hamur Olum)',
        badgeColor: 'emerald',
        dryMatter: 29.0,
        protein: 8.0,
        starch: 14.0,
        maxLimitKg: 18.0,
        approxPriceTL: 2.60,
        fieldDescription: 'Tane bağlama döneminde hasat edilmiş, iyi kıyılmış, hafif tatlımsı fermente kokulu.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Sulu veya Kart)',
        badgeColor: 'amber',
        dryMatter: 23.0,
        protein: 6.5,
        starch: 9.0,
        maxLimitKg: 14.0,
        approxPriceTL: 2.00,
        fieldDescription: 'Erken hasatta aşırı sulu kalan veya geç kalıp lifleri odunlaşmış orta kalite sorgum silajı.',
      },
    },
  },
  {
    id: 'bira-posasi',
    name: 'Bira Posası (Yaş Bira Küspesi)',
    category: 'YAS_KUSPE',
    categoryLabel: 'Yaş Küspe & Sulu Kaba Yem',
    icon: '🍺',
    generalInfo: 'Yüksek bypass protein ve lif kaynağı. Süt verimini patlatır ancak taze tüketilmeli veya tuzlanmalıdır.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Fabrikadan Taze Çıkış)',
        badgeColor: 'emerald',
        dryMatter: 23.0,
        protein: 26.0,
        starch: 5.0,
        maxLimitKg: 8.0,
        approxPriceTL: 2.20,
        fieldDescription: 'Fabrikadan taze gelmiş, kokusu ekşimemiş, küfsüz, açık kahverengi ve taneli yapıda.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Beklemiş & Sulu)',
        badgeColor: 'amber',
        dryMatter: 18.0,
        protein: 22.0,
        starch: 3.5,
        maxLimitKg: 6.0,
        approxPriceTL: 1.60,
        fieldDescription: 'Birkaç gün açıkta beklemiş, hafif asit kokusu artmış ancak küflenmemiş küspe.',
      },
    },
  },
  {
    id: 'misir-sapi-samani',
    name: 'Mısır Sapı Samanı / Koçan Samanı',
    category: 'SAMAN',
    categoryLabel: 'Saman',
    icon: '🌽',
    generalInfo: 'Tane mısır hasadından sonra tarlada kalan sapların kıyılmasıyla elde edilen ekonomik dolgu lifi.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Normal / Kuru & İnce Kıyılmış)',
        badgeColor: 'emerald',
        dryMatter: 86.0,
        protein: 4.5,
        starch: 2.5,
        maxLimitKg: 3.5,
        approxPriceTL: 2.50,
        fieldDescription: 'Biçerdöver ardından hemen balyalanmış, yağmur görmemiş, iyi kıyılmış, temiz saplar.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Orta Kalite / Yağmur Görmüş)',
        badgeColor: 'amber',
        dryMatter: 82.0,
        protein: 3.0,
        starch: 1.2,
        maxLimitKg: 2.5,
        approxPriceTL: 1.80,
        fieldDescription: 'Tarlada yağmur yemiş, kararmış veya sert parçaları fazla olan saman.',
      },
    },
  },
  {
    id: 'arpa-kirmasi',
    name: 'Arpa Kırması / Ezmesi',
    feedType: 'KESIF',
    category: 'HUBUBAT',
    categoryLabel: 'Hububat & Kırma',
    icon: '🌾',
    generalInfo: 'Süt inekçiliğinde en yaygın kullanılan temel enerji kaynağı. Hızlı sindirilen nişasta ve lif içerir. Ezme veya kaba kırma yapılması önerilir.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Dolgun / İki Sıralı / Tozsuz)',
        badgeColor: 'emerald',
        dryMatter: 89.0,
        protein: 12.0,
        starch: 55.0,
        maxLimitKg: 4.5,
        approxPriceTL: 8.50,
        fieldDescription: 'Dolgun, iri taneli, açık saman sarısı renkli, kavuzu ince, tozu elenmiş, kaba kırılmış veya buharda ezilmiş kaliteli arpa.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Cılız / Kavuzlu / İnce Tozlu)',
        badgeColor: 'amber',
        dryMatter: 88.0,
        protein: 9.5,
        starch: 46.0,
        maxLimitKg: 3.5,
        approxPriceTL: 7.20,
        fieldDescription: 'Cılız taneli, kavuz (kabuk) oranı yüksek, çok un haline gelmiş (tozlu), hektolitre ağırlığı düşük arpa.',
      },
    },
  },
  {
    id: 'misir-kirmasi',
    name: 'Mısır Kırması / Ezmesi',
    feedType: 'KESIF',
    category: 'HUBUBAT',
    categoryLabel: 'Hububat & Kırma',
    icon: '🌽',
    generalInfo: 'En yüksek nişasta ve bypass enerji konsantrasyonuna sahip tane yem. Yüksek süt verimi ve kondisyon için mükemmeldir; aşırı un yapılmamalıdır.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Kuru / Sert Sarı Tane / Yüksek Nişasta)',
        badgeColor: 'emerald',
        dryMatter: 88.0,
        protein: 9.0,
        starch: 68.0,
        maxLimitKg: 5.0,
        approxPriceTL: 9.00,
        fieldDescription: 'Kurutulmuş (%14 nem altı), camsı sert yapıda, parlak sarı, küfsüz, kaba kırılmış veya flake yapılmış kaliteli mısır.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Rutubetli / Kırık / Kısmen Tozlu)',
        badgeColor: 'amber',
        dryMatter: 85.0,
        protein: 7.5,
        starch: 58.0,
        maxLimitKg: 3.5,
        approxPriceTL: 7.50,
        fieldDescription: 'Nem oranı yüksek veya tarladan nemli gelmiş, yabancı madde oranı fazla, unlaşmış veya kırık oranı yüksek mısır.',
      },
    },
  },
  {
    id: 'bugday-kirmasi',
    name: 'Buğday Kırması',
    feedType: 'KESIF',
    category: 'HUBUBAT',
    categoryLabel: 'Hububat & Kırma',
    icon: '🌾',
    generalInfo: 'Nişastası işkembede çok hızlı parçalanan yüksek enerjili ve proteinli tane yem. Asidoz riskine karşı porsiyonu sınırlı tutulmalı ve ince öğütülmemelidir.',
    qualities: {
      firstGrade: {
        qualityGrade: '1_SINIF',
        qualityLabel: '1. Sınıf (Dolgun / Temiz Yemlik Buğday)',
        badgeColor: 'emerald',
        dryMatter: 89.0,
        protein: 13.0,
        starch: 62.0,
        maxLimitKg: 3.0,
        approxPriceTL: 9.50,
        fieldDescription: 'Dolgun, kızışmamış, yabancı ottan temizlenmiş, kaba kırılmış veya silindirde ezilmiş temiz buğday.',
      },
      secondGrade: {
        qualityGrade: '2_SINIF',
        qualityLabel: '2. Sınıf (Cılız / Süne Zararlı / Unlaşmış)',
        badgeColor: 'amber',
        dryMatter: 88.0,
        protein: 10.5,
        starch: 54.0,
        maxLimitKg: 2.0,
        approxPriceTL: 8.00,
        fieldDescription: 'Cılız, süne veya böcek zararı görmüş, değirmende fazla un haline gelmiş (asidoz riski çok yüksek) buğday.',
      },
    },
  },
];
